AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 with Apache Web Server

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  RamaWebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  RamaWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}"
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref RamaWebSecurityGroup
      Tags:
        - Key: Name
          Value: rama-apache-web-server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>CloudFormation Deployment Successful</h1>" > /var/www/html/index.html

Outputs:
  WebsiteURL:
    Value: !Sub "http://${RamaWebServer.PublicIp}"