AWSTemplateFormatVersion: '2010-09-09'

Description: Create S3 Bucket

Parameters:
  EnvironmentName:
    Type: String
    Default: dev

Resources:
  DemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${EnvironmentName}-demo-bucket-syed"

Outputs:
  BucketName:
    Value: !Ref DemoBucket